### ISSUE TITLE
Bump Node to v20

### ISSUE THREAD

**Issue by LanceMcCarthy** [kzrnm/get-net-sdk-project-versions-action#133]
Hi @kzrnm Can you push a new build v1.4.0 so that the runner uses Node v20? thanks!

**Comment by kzrnm** [comment]
Wait a minute.

**Comment by kzrnm** [comment]
@LanceMcCarthy v2 has been released. Please use `kzrnm/get-net-sdk-project-versions-action@v2`.

**Comment by LanceMcCarthy** [comment]
Fantastic, thanks for quick response... just in time for my release 🎉
